catalogs:
  peer:
    "@typescript-eslint/eslint-plugin": "^8.31.0"
    "@typescript-eslint/parser": "^8.31.0"
    "eslint": "^9.25.1"
    "eslint-config-prettier": "^10.1.2"
    "eslint-plugin-format": "^1.0.1"
    "eslint-plugin-vue": "^10.0.0"
    "eslint-plugin-prettier": "^5.2.6"
    "prettier": "^3.5.3"
    "vue-eslint-parser": "^10.1.3"
  prod:
    "@antfu/install-pkg": "^1.0.0"
    "@clack/prompts": "^0.10.1"
    "@eslint/js": "^9.25.1"
    "@stylistic/eslint-plugin": "^4.2.0"
    "eslint-plugin-simple-import-sort": "^12.1.1"
    "globals": "^16.0.0"
    "local-pkg": "^1.1.1"
  dev:
    "@eslint/config-inspector": "^1.0.2"
    "@types/node": "^22.15.2"
    "@typescript-eslint/eslint-plugin": "^8.31.0"
    "@typescript-eslint/parser": "^8.31.0"
    "bumpp": "^10.1.0"
    "eslint": "^9.25.1"
    "eslint-config-prettier": "^10.1.2"
    "eslint-plugin-format": "^1.0.1"
    "eslint-plugin-vue": "^10.0.0"
    "eslint-plugin-prettier": "^5.2.6"
    "jiti": "^2.4.2"
    "prettier": "^3.5.3"
    "tsup": "^8.4.0"
    "typescript": "^5.8.3"
    "vue-eslint-parser": "^10.1.3"
