catalogs:
  peer:
    "@eslint-react/eslint-plugin": "^2.0.0"
    "@typescript-eslint/eslint-plugin": "^8.44.1"
    "@typescript-eslint/parser": "^8.44.1"
    "eslint": "^9.36.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-react-hooks": "^5.2.0"
    "eslint-plugin-react-refresh": "^0.4.22"
    "eslint-plugin-format": "^1.0.2"
    "eslint-plugin-vue": "^10.5.0"
    "eslint-plugin-prettier": "^5.5.4"
    "prettier": "^3.6.2"
    "vue-eslint-parser": "^10.2.0"
  prod:
    "@antfu/install-pkg": "^1.1.0"
    "@clack/prompts": "^0.11.0"
    "@eslint/js": "^9.36.0"
    "@stylistic/eslint-plugin": "^5.4.0"
    "eslint-plugin-simple-import-sort": "^12.1.1"
    "globals": "^16.4.0"
    "local-pkg": "^1.1.2"
  dev:
    "@eslint-react/eslint-plugin": "^2.0.0"
    "@eslint/config-inspector": "^1.3.0"
    "@types/node": "^22.18.6"
    "@typescript-eslint/eslint-plugin": "^8.44.1"
    "@typescript-eslint/parser": "^8.44.1"
    "bumpp": "^10.2.3"
    "eslint": "^9.36.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-react-hooks": "^5.2.0"
    "eslint-plugin-react-refresh": "^0.4.22"
    "eslint-plugin-format": "^1.0.2"
    "eslint-plugin-vue": "^10.5.0"
    "eslint-plugin-prettier": "^5.5.4"
    "jiti": "^2.6.0"
    "prettier": "^3.6.2"
    "simple-git-hooks": "^2.13.1"
    "tsdown": "^0.15.4"
    "typescript": "^5.9.2"
    "vue-eslint-parser": "^10.2.0"
