catalogs:
  binary:
    "eslint": "^10.0.1"
    "lint-staged": "^16.2.7"
    "prettier": "^3.8.1"
  dev:
    "@eslint/config-inspector": "^1.4.2"
  helper:
    "@antfu/install-pkg": "^1.1.0"
    "@clack/prompts": "^1.0.1"
    "globals": "^17.3.0"
    "local-pkg": "^1.1.2"
  infra:
    "bumpp": "^10.4.1"
    "cspell": "^9.6.4"
    "simple-git-hooks": "^2.13.1"
    "tsdown": "^0.20.3"
    "typescript": "^5.9.3"
  optional:
    "@eslint-react/eslint-plugin": "^2.13.0"
    "@typescript-eslint/eslint-plugin": "^8.56.0"
    "@typescript-eslint/parser": "^8.56.0"
    "eslint-config-prettier": "^10.1.8"
    "eslint-plugin-format": "^1.4.0"
    "eslint-plugin-prettier": "^5.5.5"
    "eslint-plugin-react-hooks": "^7.0.1"
    "eslint-plugin-react-refresh": "^0.5.0"
    "eslint-plugin-vue": "^10.8.0"
    "vue-eslint-parser": "^10.4.0"
  required:
    "@eslint/js": "^9.39.3"
    "@stylistic/eslint-plugin": "^5.9.0"
    "eslint-plugin-import": "^2.32.0"
    "eslint-plugin-simple-import-sort": "^12.1.1"
    "eslint-plugin-unicorn": "^63.0.0"
  typing:
    "@eslint/core": "^1.1.0"
    "@types/node": "^25.3.0"
